config/routes.rb
Rails.application.routes.draw do

  resources :addresses
  resources :foods
  resources :users

  get 'sign_in' => 'sessions#new'
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  
    root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :city, presence: true
  validates :street, presence: true
  validates :number, presence: true
  validates :cep, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    validates :name,presence: true
    validates :price,presence: true
    validates :photo,presence: true
    validates :info,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6},on: :create
  has_many :addresses
  validates :email, presence: true, length: {maximum: 260}, uniqueness: {case_sensitive: false}
  before_save { self.email = email.downcase }
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  def create
    @address = Address.new(address_params)
    @address.user_id=@current_user.id
    respond_to do |format|
      if @address.save
        format.html { redirect_to @current_user, notice: 'Address was successfully created.' }

        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @address = Address.new
  end

  def edit
  end

  def update
    @address = Address.find(params[:id]) 
    if @address.update_attributes(address_params)
      redirect_to user_path(@current_user)
    else
      render action: :edit
    end
  end

  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to @current_user, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_address
    @address = Address.find(params[:id])
  end
    def address_params
      params.require(:address).permit(:city, :street, :number, :complement, :cep, :user_id)
    end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :current_user
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  def new
    @food = Food.new
  end

  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def edit
  end
  

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to foods_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location:food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }

        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
   
  end

  def index
    @foods=Food.all
  end
  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :price, :info, :photo, :kind)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_acess, except: [:destroy]
  before_action :redirect, only: [:sign_in]
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in(@user)
      redirect_to @user
    else
      render 'new'
    end 
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
  def redirect
    if !logged_in?
      redirect @current_user
    end

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :redirect, only: [:show,:index]
  before_action :block_not_logged, except: [:create, :new]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id]) 
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to sign_in_path, notice: 'Usuario foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id]) 
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render action: :edit
    end
   end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario destruido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :admistrador, :password, :password_confirmation)
    end
    def user_params_without_password
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
      user_params
   end
   def redirect
    if logged_in?
      if (@user!=@current_user && @current_user.admistrador!=true)
        redirect_to @current_user
      end
    end
   end
   def block_not_logged
    if !logged_in?
      redirect_to root_path
    end
  end

  end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(usuario)
        session[:user_id] = usuario.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_acess
        if current_user.present?
            redirect_to user_path(current_user)
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def sign_out
        session.delete(:user_id)
        @current_user =nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form|%>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :rua %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :number %>
  </div>
  <div class="field">
    <%= form.label :complemento %>
    <%= form.text_field :complement%>
  </div>
  
  <div class="field">
    <%= form.label :cep %>
    <%= form.text_field :cep%>
  </div>

  

  <div class="actions">
    <%= form.submit :enviar %>
  </div>
<% end %>

app/views/addresses/create.html.erb
<h1>Addresses#create</h1>
<p>Find me in app/views/addresses/create.html.erb</p>

app/views/addresses/edit.html.erb
<div class='address'>
<h2>Editando endereço</h2>
<%= render  "form", address: @address %>
<div class='a'><%= link_to  "voltar",user_path(@current_user) %></div>
</div>

app/views/addresses/new.html.erb
<div class='address'>
<h2>Novo endereço</h2>
<%= render  "form", address: @address%>
<%= link_to  "voltar",user_path(@current_user) %>
</div>

app/views/addresses/update.html.erb
<h1>Addresses#update</h1>
<p>Find me in app/views/addresses/update.html.erb</p>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form|%>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :preço %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info %>
  </div>
  <div class="field">
    <%= form.label :tipo %>
    <%= form.select :kind,['pizza salgada','pizza doce','promoção','bebida'] %>
  </div>
  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/edit.html.erb
<h2>Editar produto</h2>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<div class="food_index">
  <h2>Cardápio</h2>
  <% if logged_in?%>
    <% if @current_user.admistrador==true %>
      <div class='aux'><%= link_to  "adicionar produto", new_food_path %></div>
    <%end%>
  <%end%>  
  <h2>Pizzas Salgadas</h2>
  <% (@foods.where kind:'pizza salgada').each do |food| %>
    <ul>
      <li><%= food.name %></li>
      
      <li>preço:<%= food.price %>reais</li>
      <li>ingredientes: <%= food.info %><li>
      
      <li><%= link_to 'ver mais', food %></li>
      <% if logged_in?%>
        <% if @current_user.admistrador==true %>
          <li><%= link_to 'editar', edit_food_path(food) %></li>
          <li><%= link_to 'destruir', food, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        
        <%end%>
      <%end%>
      </ul>
  <% end %>
    <h2>Pizzas Doces</h2>
  <% (@foods.where kind:'pizza doce').each do |food| %>
    <ul>
     <li><%= food.name %></li>
      
      <li>preço:<%= food.price %>reais</li>
      <li>ingredientes: <%= food.info %><li>
      <li><%= link_to 'ver mais', food %></li>
      <% if @current_user.admistrador==true %>
        <li><%= link_to 'editar', edit_food_path(food) %></li>
        <li><%= link_to 'destroir', food, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
      <%end%>
  <% end %>

    <h2>Bebidas</h2>
  <% (@foods.where kind:'bebida').each do |food| %>
    <ul>
      <li><%= food.name %></li>
      
      <li>preço:<%= food.price %>reais</li>
      <li>ingredientes: <%= food.info %><li>
      <li><%= link_to 'ver mais', food %></li>
      <% if logged_in?%>
        <% if @current_user.admistrador==true %>
          <li><%= link_to 'editar', edit_food_path(food) %></li>
          <li><%= link_to 'destruir', food, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <%end%>
      <%end%>
      </ul>
  <% end %>

    <h2>Promoção</h2>
  <% (@foods.where kind:'promoção').each do |food| %>
    <ul>
      <li><%= food.name %></li>
      
      <li>preço:<%= food.price %>reais</li>
      <li>ingredientes: <%= food.info %><li>
      <li><%= link_to 'ver mais', food %></li>
      <% if logged_in?%>
        <% if @current_user.admistrador==true %>
          <li><%= link_to 'editar', edit_food_path(food) %></li>
          <li><%= link_to 'destruir', food, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <%end%>
      <%end%>
      </ul>
  <% end %>
</div>

app/views/foods/new.html.erb
<h2>Novo produto</h2>

<%= render 'form', food: @food %>

app/views/foods/show.html.erb
<div class='food_show'>
    <h2><%=@food.name%></h2>
    <%= image_tag(@food.photo)%>
    <p>Ingrediente: <%=@food.info%></p>
    <p>Preço: <%=@food.price%></p>
</div>

app/views/foods/update.html.erb
<h1>Foods#update</h1>
<p>Find me in app/views/foods/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeDePizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <section class="bar">
        <nav>
          <ul>
            <li><%= link_to 'Home', root_path %></li>    
            <%if !logged_in?%>
              <li><%=link_to 'Login', sign_in_path%></li>
            <% else %>
              <li><%=link_to 'Seu Perfil',user_path(@current_user)%></li>
            <% end %>
            <li><%= link_to 'Cardapio', foods_path%></li>
          
          </ul>
        <nav>
        <%= image_tag('logo.png')%>
      </section>
      <section class='title'>
      <h1>Pé de Pizza</h1>
      <%= image_tag('ketchup.png')%>
      </section class='tt'>
      
    </header>
    
    <%= yield %>
    
   
    
    <footer>
      <div>
      <a href="#">facebook |</a>
      
      <a href="#">instagram</a>
    </footer>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="wrapper">
<h2>Quem somos</h2>
<p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.”</p>

<section class='prom'>
    <h2>Promoções</h2>
    <% for prom in (Food.where(kind:'promoção'))%>
        <h3><%=prom.name%></h3>
        <%= image_tag(prom.photo)%>
        <p> info:<%= prom.info%></p>
    <%end%>
    </section>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      

      <ul>
      <li>Os seguintes erros ocorreram</li>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <% @adm=User.find_by admistrador:true%>
  <% if !(@current_user.nil?)&&(@current_user.admistrador==true) || @adm.nil?%>
  <div class="field">
    <%= form.label :admistrador %>
    <%= form.check_box :admistrador %>
  </div>
  <% end %>
  <% if !logged_in? %>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='user_edit'>
<h2>Editando usuario</h2>

<%= render 'form', user: @user %>


<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="user_index">
  <p id="notice"><%= notice %></p>

  <h2>Usuarios registrados</h2>


  
  <% @users.each do |user| %>
    <ul>
      
      <li>Nome: <%= user.name %></li>
      <li>Email: <%= user.email %></li>
      
      <li><%=link_to 'Show', user %></li>
      <li><%= link_to 'Edit', edit_user_path(user) %></li>
      <li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    
    </ul>
  <% end %>
  
</div>

app/views/users/new.html.erb
<div class='new_user'>
<h2>Cadastre-se!!</h2>

<%= render 'form', user: @user %>


<div>

app/views/users/show.html.erb
<div class="user_show">
  
  <p id="notice"><%= notice %></p>
  <h2>Página de <%=@user.name%></h2>
  <ul>
  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>
  <li>
  
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

  
  <li><%= link_to 'Edit', edit_user_path(@user) %></li>
  
  <% if @user==@current_user%>
    <li><%=link_to 'Novo endereço',new_address_path%></li>
    <li><%= link_to  "Sair", sign_out_path,method: :delete %></li>
    <% if @user.admistrador==true%>
      <li><%= link_to  "Lista de usuario", users_path %></li>
    <% end %>
  <%end%>
  </ul>
  <%@user.addresses.each do |add|%>
  <h2>Seus endereços</h2>
  <ul>
    <li>Cidade: <%= add.city %></li>
    <li>Rua: <%= add.street %></li>
    <li>numero: <%= add.number %></li>
    <li>complemento: <%= add.complement %></li>
    <li> cep:<%=add.cep%></li>
    <li><%= link_to  "remover", add,method: :delete %></li>
    <li><%= link_to  "editar", edit_address_path(add) %></li>
   
  </ul>
  <%end%>
</div>